// AUTO-GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen:registry`.
/* eslint-disable */
export const registryBundle = {
  "version": 1,
  "updatedAt": "2026-06-08T00:00:00Z",
  "chains": [
    {
      "chainId": 11155111,
      "name": "ethereum-sepolia",
      "displayName": "Ethereum Sepolia",
      "nativeSymbol": "ETH",
      "coinType": 60,
      "rpcEnv": "RPC_ETHEREUM_SEPOLIA",
      "explorerTxUrl": "https://sepolia.etherscan.io/tx/{hash}",
      "explorerAddressUrl": "https://sepolia.etherscan.io/address/{address}",
      "assets": [
        {
          "type": "native",
          "symbol": "ETH",
          "name": "Ether",
          "decimals": 18
        },
        {
          "type": "erc20",
          "symbol": "DEMO",
          "name": "Demo Token",
          "decimals": 18,
          "address": "0x15fe2D2D221F2B3Ee96D230d50B496Ab5F1b8B3E",
          "deploymentBlock": 11015617
        },
        {
          "type": "erc721",
          "symbol": "KASA",
          "name": "Kasa Collectible",
          "decimals": 0,
          "address": "0x88F67A2EbD4C342496d0A477EF58F3a89BCF95F2",
          "deploymentBlock": 11015618
        }
      ]
    },
    {
      "chainId": 43113,
      "name": "avalanche-fuji",
      "displayName": "Avalanche Fuji",
      "nativeSymbol": "AVAX",
      "coinType": 60,
      "rpcEnv": "RPC_AVALANCHE_FUJI",
      "explorerTxUrl": "https://testnet.snowtrace.io/tx/{hash}",
      "explorerAddressUrl": "https://testnet.snowtrace.io/address/{address}",
      "assets": [
        {
          "type": "native",
          "symbol": "AVAX",
          "name": "Avalanche",
          "decimals": 18
        },
        {
          "type": "erc20",
          "symbol": "DEMO",
          "name": "Demo Token",
          "decimals": 18,
          "address": "0x4dBD859993952132Be0499CEF34419fc1A604867",
          "deploymentBlock": 56110521
        },
        {
          "type": "erc721",
          "symbol": "KASA",
          "name": "Kasa Collectible",
          "decimals": 0,
          "address": "0xF83a0306A284A9AF72464D58b63501a55c846873",
          "deploymentBlock": 56110523
        }
      ]
    },
    {
      "chainId": 31337,
      "name": "hardhat-local",
      "displayName": "Hardhat Local",
      "nativeSymbol": "ETH",
      "coinType": 60,
      "rpcEnv": "RPC_HARDHAT",
      "explorerTxUrl": "http://localhost:8545/tx/{hash}",
      "explorerAddressUrl": "http://localhost:8545/address/{address}",
      "assets": [
        {
          "type": "native",
          "symbol": "ETH",
          "name": "Ether",
          "decimals": 18
        },
        {
          "type": "erc20",
          "symbol": "DEMO",
          "name": "Demo Token",
          "decimals": 18,
          "address": "0x0000000000000000000000000000000000000000",
          "deploymentBlock": 0
        },
        {
          "type": "erc721",
          "symbol": "KASA",
          "name": "Kasa Collectible",
          "decimals": 0,
          "address": "0x0000000000000000000000000000000000000000",
          "deploymentBlock": 0
        }
      ]
    }
  ]
} as const;
