import { registryBundleSchema } from "./schema.js";
import { ZERO_ADDRESS } from "./consts.js";
import { toLookupKey } from "./address.js";
import type { Asset, Chain, ChainId, NativeAsset } from "./types.js";
// Generated by `pnpm gen:registry` from data/registry.json + data/chains/*.json (committed artifact).
import { registryBundle } from "./_generated/registry.data.js";

interface ChainIndex {
  readonly chain: Chain;
  readonly bySymbol: ReadonlyMap<string, Asset>;
  readonly byAddress: ReadonlyMap<string, Asset>;
  readonly native: NativeAsset;
}

function build(): Map<ChainId, ChainIndex> {
  const bundle = registryBundleSchema.parse(registryBundle);
  const out = new Map<ChainId, ChainIndex>();
  for (const chain of bundle.chains) {
    if (out.has(chain.chainId)) throw new Error(`duplicate chainId ${chain.chainId}`);
    const bySymbol = new Map<string, Asset>();
    const byAddress = new Map<string, Asset>();
    let native: NativeAsset | undefined;
    for (const asset of chain.assets) {
      const symKey = asset.symbol.toUpperCase();
      if (bySymbol.has(symKey)) {
        throw new Error(`duplicate symbol ${asset.symbol} on chain ${chain.chainId}`);
      }
      bySymbol.set(symKey, asset);
      if (asset.type === "native") {
        if (native) throw new Error(`multiple native assets on chain ${chain.chainId}`);
        native = asset;
      } else {
        const key = toLookupKey(asset.address);
        // Undeployed tokens carry the zero-address placeholder until deploy.ts fills the real
        // address — don't index those (multiple may share it) and don't treat it as a collision.
        if (key !== toLookupKey(ZERO_ADDRESS)) {
          if (byAddress.has(key)) {
            throw new Error(`duplicate address ${asset.address} on chain ${chain.chainId}`);
          }
          byAddress.set(key, asset);
        }
      }
    }
    if (!native) throw new Error(`chain ${chain.chainId} has no native asset`);
    out.set(chain.chainId, { chain, bySymbol, byAddress, native });
  }
  return out;
}

/** Frozen, validated registry — built once at module load. */
export const REGISTRY: ReadonlyMap<ChainId, ChainIndex> = build();

export function chainIndex(chainId: ChainId): ChainIndex {
  const idx = REGISTRY.get(chainId);
  if (!idx) throw new Error(`unsupported chain: ${chainId}`);
  return idx;
}
