// Bundle data/registry.json + data/chains/*.json into a single validated, statically-importable
// TS module (src/_generated/registry.data.ts) so the library works identically in browsers,
// bundlers, and raw Node — no JSON import attributes, compiles to dist like any other source.
// Committed; regenerated whenever a chain/asset data file changes.
import { mkdirSync, writeFileSync } from "node:fs";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chainSchema, manifestSchema } from "../src/schema.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p: string): unknown => JSON.parse(readFileSync(join(root, p), "utf8"));

const manifest = manifestSchema.parse(read("data/registry.json"));
const chains = manifest.chainIds.map((id) => chainSchema.parse(read(`data/chains/${id}.json`)));

const bundle = { version: manifest.version, updatedAt: manifest.updatedAt, chains };
mkdirSync(join(root, "src/_generated"), { recursive: true });
const body =
  "// AUTO-GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen:registry`.\n" +
  "/* eslint-disable */\n" +
  `export const registryBundle = ${JSON.stringify(bundle, null, 2)} as const;\n`;
writeFileSync(join(root, "src/_generated/registry.data.ts"), body);
console.log(`registry.data.ts written: ${chains.length} chains`);
